/- LEAN4 FILE AUTO GENERATED BY CQOTL PROVER FOR OBLIGATION: obligation_1 -/
/- Proof by Iván Renison -/

import QHilbert.Commons
import QHilbert.LinearMapPropositions
import QHilbert.ProjectionSubmodule

variable {𝕜 : Type*} [_inst : (RCLike 𝕜)]

local notation "𝕜²" => ((EuclideanSpace 𝕜) (Fin 2))

def lt : (ℤ → (ℤ → Bool)) := fun x y ↦ x < y

lemma obligation_1 (x' : ℤ) (x : ℤ) (i' : ℤ) (i : ℤ) (m : ℤ) :
    ((((x = x') ∧ (i = i')) → ((((lt i) m) = ((lt i') m)) ∧ ((x = x') ∧ (i = i')))) = true) := by
  simp only [lt, decide_eq_decide, and_imp, eq_iff_iff, iff_true]
  intro hx hi
  simp [hx, hi]
