/- LEAN4 FILE AUTO GENERATED BY CQOTL PROVER FOR OBLIGATION: obligation_8 -/

import LeanVeri.Commons
import LeanVeri.LinearMapPropositions
import LeanVeri.ProjectionSubmodule

variable {𝕜 : Type*} [_inst : (RCLike 𝕜)]

local notation "𝕜²" => ((EuclideanSpace 𝕜) (Fin 2))

def mu  : (Bool → 𝕜) := sorry

def P1  : 𝕜² →ₗ[𝕜] 𝕜² := ketbra1

def vplus  : 𝕜² := sorry

lemma obligation_8  :
 ∀ (rho : 𝕜² →ₗ[𝕜] 𝕜²), ∀ (pfspace : ((LinearMap.toSubmodule rho) ≤ (LinearMap.toSubmodule ((((outerProduct 𝕜) vplus) vplus) : 𝕜² →ₗ[𝕜] 𝕜²)))), ((((LinearMap.trace 𝕜) 𝕜²) (P1 * rho)) = (mu true)) := sorry