/- LEAN4 FILE AUTO GENERATED BY CQOTL PROVER FOR OBLIGATION: obligation_11 -/

import LeanVeri.Commons
import LeanVeri.LinearMapPropositions
import LeanVeri.ProjectionSubmodule

variable {𝕜 : Type*} [_inst : (RCLike 𝕜)]

local notation "𝕜²" => ((EuclideanSpace 𝕜) (Fin 2))

def iadd  : (ℤ → (Bool → ℤ)) := sorry

def lt  : (ℤ → (ℤ → Bool)) := sorry

lemma obligation_11 (x' : ℤ) (x : ℤ) (i' : ℤ) (i : ℤ) (m : ℤ) :
 ∀ (H0 : ((¬ ((((lt ((iadd i) true)) m) = ((lt ((iadd i') true)) m)) ∧ ((x = x') ∧ (((iadd i) true) = ((iadd i') true))))) = true)), ((¬ ((((lt i) m) = ((lt i') m)) ∧ ((x = x') ∧ (i = i')))) = true) := sorry