/- LEAN4 FILE AUTO GENERATED BY CQOTL PROVER FOR OBLIGATION: obligation_3 -/

import LeanVeri.Commons
import LeanVeri.LinearMapPropositions
import LeanVeri.ProjectionSubmodule

variable {𝕜 : Type*} [_inst : (RCLike 𝕜)]

local notation "𝕜²" => ((EuclideanSpace 𝕜) (Fin 2))

def lt  : (ℤ → (ℤ → Bool)) := sorry

lemma obligation_3 (x' : ℤ) (x : ℤ) (i' : ℤ) (i : ℤ) (m : ℤ) :
 ∀ (H0 : ((¬ (((lt i) m) ∧ ((x = x') ∧ (i = i')))) = true)), ((¬ ((((lt i) m) ∧ ((lt i') m)) ∧ ((x = x') ∧ (i = i')))) = true) := sorry