/- LEAN4 FILE AUTO GENERATED BY CQOTL PROVER FOR PROOF OBLIGATIONS -/
import LeanVeri.Commons
import LeanVeri.LinearMapPropositions
import LeanVeri.ProjectionSubmodule

variable {𝕜 : Type*} [RCLike 𝕜]

local notation "𝕜²" => EuclideanSpace 𝕜 (Fin 2)

def μ : Fin 2 → 𝕜 := sorry

def ket0bra0  : 𝕜² →ₗ[𝕜] 𝕜² := sorry

lemma obligation (ρ : 𝕜² →ₗ[𝕜] 𝕜²) (h1 : ρ.isDensityOperator) (h2 : ρ.toSubmodule ≤ ketbraP.toSubmodule) :
  LinearMap.trace 𝕜 𝕜² (ket0bra0 * ρ) = μ 0 := sorry
