/- LEAN4 FILE AUTO GENERATED BY CQOTL PROVER FOR PROOF OBLIGATIONS -/

import LeanVeri.Commons
import LeanVeri.LinearMapPropositions

def lt : ℤ → ℤ → Bool := sorry

lemma obligation (b b' : Bool) (x x' i i' m : ℤ) :
  (((¬ ((lt i) m) ∧ ¬ ((lt i') m)) ∧ ((x = x') ∧ (i = i'))) → (x = x')) = true := by sorry
