/- LEAN4 FILE AUTO GENERATED BY CQOTL PROVER FOR PROOF OBLIGATIONS -/

import LeanVeri.Commons
import LeanVeri.LinearMapPropositions

variable {𝕜 : Type*} [_inst : (RCLike 𝕜)]

local notation "𝕜²" => ((EuclideanSpace 𝕜) (Fin 2))

noncomputable def H : 𝕜² →ₗ[𝕜] 𝕜² := sorry

noncomputable def ketPlus : 𝕜² := sorry

def ket0bra0 : 𝕜² →ₗ[𝕜] 𝕜² := sorry

def ket1bra1 : 𝕜² →ₗ[𝕜] 𝕜² := sorry

lemma obligation :
 ((LinearMap.LoewnerOrder ket0bra0) (((outerProduct 𝕜) (H ketPlus)) (H ketPlus))) := sorry
