/- LEAN4 FILE AUTO GENERATED BY CQOTL PROVER FOR PROOF OBLIGATIONS -/

import LeanVeri.Commons
import LeanVeri.LinearMapPropositions

def lt : ℤ → ℤ → Bool := fun x y => x < y

lemma obligation (b': Bool)  (b : Bool) (x' : ℤ) (x : ℤ) (i' : ℤ) (i : ℤ) (m : ℤ) (n : ℤ) :
  !((x == x') ∧ (i == i')) ∨ ((((lt i) m) == ((lt i') m)) ∧ ((x == x') ∧ (i == i'))) == true := sorry
