/- LEAN4 FILE AUTO GENERATED BY CQOTL PROVER FOR PROOF OBLIGATIONS -/

import LeanVeri.Commons
import LeanVeri.LinearMapPropositions

variable {𝕜 : Type*} [_inst : (RCLike 𝕜)]

local notation "𝕜²" => ((EuclideanSpace 𝕜) (Fin 2))

def lt : ℤ → ℤ → Bool := sorry

lemma obligation (b' b : Bool) (x' x i' i m n : ℤ) :
  !((x == x') ∧ (i == i')) ∨ ((((lt i) m)) ∧ ((x == x') ∧ (i == i'))) == true := by
  sorry
