/- LEAN4 FILE AUTO GENERATED BY CQOTL PROVER FOR PROOF OBLIGATIONS -/

import LeanVeri.Commons
import LeanVeri.LinearMapPropositions
import LeanVeri.ProjectionSubmodule

variable {𝕜 : Type*} [_inst : (RCLike 𝕜)]

local notation "𝕜²" => ((EuclideanSpace 𝕜) (Fin 2))

def μ  : Bool → 𝕜 := sorry

def P1 : 𝕜² →ₗ[𝕜] 𝕜² := ketbra1

lemma obligation (ρ : 𝕜² →ₗ[𝕜] 𝕜²) (h1 : (LinearMap.isDensityOperator ρ)) (h2 : ((LinearMap.toSubmodule ρ) ≤ (LinearMap.toSubmodule zeroOperator))) :
 ((((LinearMap.trace 𝕜) 𝕜²) (P1 * ρ)) = (μ true)) := sorry
