/- LEAN4 FILE AUTO GENERATED BY CQOTL PROVER FOR OBLIGATION: obligation_5 -/

import LeanVeri.Commons
import LeanVeri.LinearMapPropositions
import LeanVeri.ProjectionSubmodule

variable {𝕜 : Type*} [_inst : (RCLike 𝕜)]

local notation "𝕜²" => ((EuclideanSpace 𝕜) (Fin 2))

def iadd  : (ℤ → (Bool → ℤ)) := sorry

def lt  : (ℤ → (ℤ → Bool)) := sorry

lemma obligation_5 (b' : Bool) (b : Bool) (x' : ℤ) (x : ℤ) (i' : ℤ) (i : ℤ) (m : ℤ) :
 ((((((lt i) m) ∧ ((lt i') m)) ∧ ((((x = x') ∧ (i = i')) ∧ (b = b')) ∧ (((iadd x) b) = ((iadd x') b')))) → ((((lt i) m) = ((lt i') m)) ∧ ((((iadd x) b) = ((iadd x') b')) ∧ (i = i')))) = true) := sorry