/- LEAN4 FILE AUTO GENERATED BY CQOTL PROVER FOR PROOF OBLIGATIONS -/

import LeanVeri.Commons
import LeanVeri.LinearMapPropositions
import LeanVeri.ProjectionSubmodule

variable {𝕜 : Type*} [_inst : (RCLike 𝕜)]

local notation "𝕜²" => ((EuclideanSpace 𝕜) (Fin 2))

def μ  : Bool → 𝕜 := sorry

def ket1bra1  : 𝕜² →ₗ[𝕜] 𝕜² := sorry

def ketPbraP  : 𝕜² →ₗ[𝕜] 𝕜² := sorry

lemma obligation1 (ρ1 : 𝕜² →ₗ[𝕜] 𝕜²) (h1 : (LinearMap.isDensityOperator ρ1)) (h2 : ((LinearMap.toSubmodule ρ1) ≤ (LinearMap.toSubmodule ketPbraP))) :
 ((((LinearMap.trace 𝕜) 𝕜²) (ket1bra1 * ρ1)) = (μ true)) := sorry